import {
  Boxes,
  BrainCircuit,
  BriefcaseBusiness,
  BookOpen,
  Building2,
  ChartNoAxesCombined,
  Code2,
  Cpu,
  Database,
  Factory,
  FileText,
  Filter,
  Flame,
  FolderOpen,
  Folders,
  GraduationCap,
  Headphones,
  HeartPulse,
  Landmark,
  Layers3,
  Network,
  PackageSearch,
  ShieldCheck,
  Sparkles,
  Tag,
  Tags,
  Target,
  Truck,
  UserRound,
  Users,
  Video,
  Workflow,
  Wrench,
  Zap
} from 'lucide-react';

// Stored registry values resolve only through this curated mapping. It keeps
// server-provided icon keys declarative and prevents arbitrary SVG/component
// injection in both the public vault and the admin UI.
export const TAXONOMY_ICON_COMPONENTS = Object.freeze({
  'book-open': BookOpen,
  'brain-circuit': BrainCircuit,
  'briefcase-business': BriefcaseBusiness,
  'building-2': Building2,
  boxes: Boxes,
  'chart-no-axes-combined': ChartNoAxesCombined,
  'code-2': Code2,
  cpu: Cpu,
  database: Database,
  factory: Factory,
  filter: Filter,
  folder: FolderOpen,
  folders: Folders,
  'graduation-cap': GraduationCap,
  'heart-pulse': HeartPulse,
  landmark: Landmark,
  headphones: Headphones,
  layers: Layers3,
  network: Network,
  'package-search': PackageSearch,
  'shield-check': ShieldCheck,
  sparkles: Sparkles,
  tag: Tag,
  tags: Tags,
  target: Target,
  truck: Truck,
  'user-round': UserRound,
  users: Users,
  workflow: Workflow,
  wrench: Wrench,
  zap: Zap,
  // UI-only compatibility identifiers used by the existing smart-collection
  // fallback. Registry writes themselves are constrained by the server list.
  book: BookOpen,
  code: Code2,
  file: FileText,
  flame: Flame,
  shield: ShieldCheck,
  video: Video
});

export const TAXONOMY_ICON_OPTIONS = Object.freeze([
  { value: 'factory', label: 'GYÁR / IPARÁG' },
  { value: 'zap', label: 'ZAP / TECHNOLÓGIA' },
  { value: 'target', label: 'CÉLKERESZT / SZEREPKÖR' },
  { value: 'user-round', label: 'EGYÉNI SZEREPKÖR' },
  { value: 'users', label: 'CSOPORT' },
  { value: 'layers', label: 'RÉTEGEK / TÉMA' },
  { value: 'folder', label: 'MAPPA' },
  { value: 'folders', label: 'MAPPAKÉSZLET' },
  { value: 'tag', label: 'CÍMKE' },
  { value: 'tags', label: 'CÍMKECSOPORT' },
  { value: 'network', label: 'HÁLÓZAT' },
  { value: 'sparkles', label: 'SMART' },
  { value: 'flame', label: 'KIEMELT' },
  { value: 'headphones', label: 'AUDIO' },
  { value: 'video', label: 'VIDEÓ' },
  { value: 'brain-circuit', label: 'AI / GONDOLKODÁS' },
  { value: 'filter', label: 'SZŰRŐ / FÁJDALOMPONT' },
  { value: 'boxes', label: 'RENDSZERKOMPONENS' },
  { value: 'workflow', label: 'FOLYAMAT' },
  { value: 'chart-no-axes-combined', label: 'ELEMZÉS / MUTATÓ' },
  { value: 'briefcase-business', label: 'ÜZLETI' },
  { value: 'wrench', label: 'MŰSZAKI' },
  { value: 'code-2', label: 'SPEC / KÓD' },
  { value: 'cpu', label: 'SZÁMÍTÁS' },
  { value: 'landmark', label: 'INTÉZMÉNY' },
  { value: 'heart-pulse', label: 'ÁLLAPOT / EGÉSZSÉG' },
  { value: 'truck', label: 'LOGISZTIKA' },
  { value: 'building-2', label: 'ÉPÜLET / TELEPHELY' },
  { value: 'package-search', label: 'ALKATRÉSZ / KERESÉS' },
  { value: 'graduation-cap', label: 'KÉPZÉS' },
  { value: 'shield-check', label: 'BIZTONSÁG' },
  { value: 'database', label: 'SQL / ADATBÁZIS' },
  { value: 'book-open', label: 'TUDÁSTÁR' }
]);

export const normalizeTaxonomyIconKey = (value, fallback = 'tag') => (
  Object.hasOwn(TAXONOMY_ICON_COMPONENTS, value) ? value : fallback
);
